### ISSUE TITLE
Unwanted configurations in `.vscode/settings.json`

### ISSUE THREAD

**Issue by qwerty541** [rickstaa/empty-issues-closer-action#167]
I think that configurations which change vscode interface color better to keep in user's configurations file instead of workspace's.

https://github.com/rickstaa/empty-issues-closer-action/blob/d4cd3e287b0cf093d66197fc2867f32f40f18182/.vscode/settings.json#L2C1-L17C31

@rickstaa If you agree, I can create a PR, or you can do it if you want.

**Comment by rickstaa** [comment]
Your right. I don't know how these files ended up on the remote. I removed them in https://github.com/rickstaa/empty-issues-closer-action/pull/175. Thanks a lot!
